### ISSUE TITLE
I got a $1000 bill in one month of running this code several times per day.

### ISSUE THREAD

**Issue by ryanpeach** [aws-samples/aws-nuke-account-cleanser-example#10]
https://github.com/aws-samples/aws-nuke-account-cleanser-example/blob/8e63b4911bc40a0da751b13108081313fb5f6ab0/nuke-cfn-stack.yaml#L240

This is a completely unacceptable default size for a project of this type. It could easily break the bank.

> BUILD_GENERAL1_2XLARGE: Use up to 145 GB memory, 72 vCPUs, and 824 GB of SSD storage for builds. This compute type supports Docker images up to 100 GB uncompressed.

Rediculous.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-environment.html#cfn-codebuild-project-environment-computetype

I recommend setting it to BUILD_GENERAL1_SMALL

EDIT: LAMBDA wont work because it has a 15min timeout https://aws.amazon.com/blogs/devops/aws-codebuild-adds-support-for-aws-lambda-compute-mode/

**Comment by ryanpeach** [comment]
Also you can change the "Type" to "ARM_CONTAINER" to make it even cheaper https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-compute-types.html

**Comment by awsree** [comment]
Addressed compute type update to BUILD_GENERAL1_SMALL
