### ISSUE TITLE
The Stack is deleting itself  😑

### ISSUE THREAD

**Issue by Rumplown** [aws-samples/aws-nuke-account-cleanser-example#4]
When running in non dry run, this stack is nuking itself and deleting its own resources...

It's a bit dumb because this really meet my usecase with the parallel tasking and the mail report, but yea, as of today  not perfect and need a little tweeking with role permissions.

**Comment by awsree** [comment]
Thanks for the comment. I don’t think the stack would nuke itself - as long as you have the right tags and filters applied as configured in the config update python class. The dry run results should not vary with the actual. Let me know if you have more details/output - I’m updating few other things with the code and also more fine tuned README shortly ! Stay tuned

**Comment by awsree** [comment]
I added tags and updated. If you do see that happen for your resources, make sure to add tags for all the stack resources that you do not want to delete with this value.
tag:DoNotNuke: "True"
