### ISSUE TITLE
CodeBuild job fails when 0 matches by grep

### ISSUE THREAD

**Issue by jehodges** [aws-samples/aws-nuke-account-cleanser-example#5]
https://github.com/aws-samples/aws-nuke-account-cleanser-example/blob/c56414f982a701ff2257869313a7622626f1a7ee/nuke-cfn-stack.yaml#L402
https://github.com/aws-samples/aws-nuke-account-cleanser-example/blob/c56414f982a701ff2257869313a7622626f1a7ee/nuke-cfn-stack.yaml#L408

When there are 0 matches from grep it returns an exit status 1 causing CodeBuild to interpret the command as having failed. I've worked around this by adding a || true in the command

`cat aws-nuke.log | grep -c " - would remove" || true >> email_template.txt`

**Comment by awsree** [comment]
> https://github.com/aws-samples/aws-nuke-account-cleanser-example/blob/c56414f982a701ff2257869313a7622626f1a7ee/nuke-cfn-stack.yaml#L402
> 
> https://github.com/aws-samples/aws-nuke-account-cleanser-example/blob/c56414f982a701ff2257869313a7622626f1a7ee/nuke-cfn-stack.yaml#L408
> 
> When there are 0 matches from grep it returns an exit status 1 causing CodeBuild to interpret the command as having failed. I've worked around this by adding a || true in the command
> 
> `cat aws-nuke.log | grep -c " - would remove" || true >> email_template.txt`

Hey thanks for the comment. Verified and will add the fix. I think i added that to cover in line 422 and 424 , but missed here.
Thanks!

**Comment by awsree** [comment]
Updated and added changes to the repo!
