### ISSUE TITLE
nuke is not a recognized option of aws-nuke

### ISSUE THREAD

**Issue by christophelimpalair** [aws-samples/aws-nuke-account-cleanser-example#6]
👋 First off, thanks for building this project. The mode of delivery is quite clever and perfect for a project I'm working on. As I've tested this out, I've run across an error with this section of the CF stack template:

```
- |
if [ "$AWS_NukeDryRun" = "true" ]; then
    for file in $(ls nuke_config_$NukeTargetRegion*) ; do aws-nuke -c $file --force --profile nuke 2>&1 |tee -a aws-nuke.log; done
elif [ "$AWS_NukeDryRun" = "false" ]; then
    for file in $(ls nuke_config_$NukeTargetRegion*) ; do aws-nuke -c $file --force --no-dry-run --profile nuke 2>&1 |tee -a aws-nuke.log; done
else
    echo "Couldn't determine Dryrun flag...exiting"
exit 1
fi
```

This errors out saying that `nuke` is not a recognized option of `aws-nuke`. In searching for other reference material, I don't see that option being used or even part of aws-nuke, and removing it gets rid of the error and leads to successful aws-nuke execution. Am I missing something here?

**Comment by awsree** [comment]
This is not an app issue !
