### ISSUE TITLE
why general1.2xlarge instances for CodeBuild?

### ISSUE THREAD

**Issue by felix-iw** [aws-samples/aws-nuke-account-cleanser-example#7]
Is there any specific reason why you use the quite expensive instance type "general1.2xlarge"?
Wouldn't be a smaller instance type sufficient?

**Comment by wshelley** [comment]
I just spotted this too. 145 GB memory, 72 vCPUs seems a bit overkill for a simple script!

I'm not sure what the 120 second delay is for either....
https://github.com/aws-samples/aws-nuke-account-cleanser-example/blob/8e63b4911bc40a0da751b13108081313fb5f6ab0/nuke-cfn-stack.yaml#L365

**Comment by ryanpeach** [comment]
https://github.com/aws-samples/aws-nuke-account-cleanser-example/issues/10

**Comment by awsree** [comment]
Hey agree ! the compute is overkill, I sent a request for an updated PR to modify this, 
I also added the --max-wait-retries - to avoid Nuke continuously re-trying for resources waiting/Pending state
