### ISSUE TITLE
email_template.txt file to big for SNS topic

### ISSUE THREAD

**Issue by ubpomelo** [aws-samples/aws-nuke-account-cleanser-example#8]
What would be the best way to handle the Notification template? The job is failing due to the size of the email_template.txt file when publishing the message to SNS.

![image](https://github.com/aws-samples/aws-nuke-account-cleanser-example/assets/127771343/ff34e6d5-9cec-4674-9274-0bb3928a1869)

**Comment by awsree** [comment]
The email file contents can vary based on the number of resources on a particular day that Nuke is trying to delete. You probably have to do some log condensing and adjustments there, based on what you want to see in the email. For example if you want to see only failed resources, or just send a SUCCESS/FAILURE message always, and put the logs in an S3 bucket or so.
Refer the links here https://docs.aws.amazon.com/sns/latest/dg/large-message-payloads.html
